---
title: Hello, World!
author: Antoine Pissoort
date: "October 15, 2017"
categories:
  - R
  - Visualization
tags:
  - R
slug: hello-world
description: A short introductory post accompanying the R code for generating the
  website logo.
output:
  blogdown::html_page:
    fig_retina: 2
    fig_width: 7
    dev: svg
    #highlight: pygments
    #https://www.gokhanciflikli.com/post/hello-world/#fn2
---
###Introduction

Hello, and welcome to my new website. I will briefly lay out my MO in this post. The primary reason why I switched from my old academic website in favor of a more functional (modern?) version is one of pure convenience. Nowadays, I have been building interactive web applications, mainly [Shiny apps and dashboards](https://shiny.rstudio.com/), for work and as a hobby. Consequently, I needed a central hub to host all the apps in one outlet.[^1] Hopefully, there will also be occassional data visualization posts, as well as passing around code in R and Python.

***
###About the Website

This webpage is built by using the `blogdown` package in R. In turn, the package utilizes a static-site generator called [Hugo](https://themes.gohugo.io/), and I use a variation of the theme [cactus plus](https://themes.gohugo.io/hugo-theme-cactus-plus/).
As per the recommendation of Amber Thomas and Yihui Xie,[^2] I host my site on [netlify.com](https://netlify.com), which offers continuous deployment from a git repository. All I have to do is to create a new Markdown/RMarkdown document and within seconds it will be deployed to the website. Pretty neat.

***
###RMarkdown

Speaking of RMarkdown, the logo of the website is created using the `sunburstR` package. The data shown are not artifically constructed; the graph indeed shows the breakdown of female author inclusion patterns in IR syllabi at the LSE for the 2015-2016 academic year. Hovering on the dial will display a breadcrumb trail on the top. Below you can find the R code used to generate the graph:

```{r}
CRAN_page <- function(...) {
    file.path('https://cran.rstudio.com/src/contrib', ...)
}

## get list of currently available packages on CRAN
library(XML)
pkgs <- readHTMLTable(readLines(CRAN_page()),
                                which = 1, stringsAsFactors = FALSE)

## we love data.table
library(data.table)
setDT(pkgs)

## drop directories
pkgs <- pkgs[Size != '-']
## drop files that does not seem to be R packages
pkgs <- pkgs[grep('tar.gz$', Name)]

## package name should contain only (ASCII) letters, numbers and dot
pkgs[, name := sub('^([a-zA-Z0-9\\.]*).*', '\\1', Name)]

## grab date from last modified timestamp
pkgs[, date := as.POSIXct(`Last modified`, format = '%d-%b-%Y %H:%M')]
pkgs[, date := as.character(date)]

## keep date and name
pkgs <- pkgs[, .(name, date)]

## list of packages with at least one archived version
archives <- readHTMLTable(readLines(CRAN_page('Archive')),
                          which = 1, stringsAsFactors = FALSE)
setDT(archives)

## keep directories
archives <- archives[grep('/$', Name)]

## add packages not found in current list of R packages
archives[, Name := sub('/$', '', Name)]
pkgs <- rbind(pkgs,
              archives[!Name %in% pkgs$name, .(name = Name)],
              fill = TRUE)

## reorder pkg in alphabet order
setorder(pkgs, name)

## number of versions released is 1 for published packages
pkgs[, versions := 0]
pkgs[!is.na(date), versions := 1]

## mark archived pacakges
pkgs[, archived := FALSE]
pkgs[name %in% archives$Name, archived := TRUE]

## NA date of packages with archived versions
pkgs[archived == TRUE, date := NA]

## lookup release date of first version & number of releases
pkgs[is.na(date), c('date', 'versions') := {

    cat(name, '\n')

    ## download archive page
    page <- readLines(CRAN_page('Archive', name))

    ## extract date with regexp as HTML parsing can be slow :)
    date <- sub('.*([0-9]{2}-[A-Za-z]{3}-[0-9]{4} [0-9]{2}:[0-9]{2}).*', '\\1', page[10])

    ## convert to YYYY-mm-dd format
    date <- as.POSIXct(date, format = '%d-%b-%Y %H:%M')

    ## number of previous releases
    archived_versions <- length(page) - 9 - 4

    ## return
    list(as.character(date), versions + archived_versions)

}, by = name]

## rename cols
setnames(pkgs, 'date', 'first_release')

## order by date & alphabet
setorder(pkgs, first_release, name)
pkgs[, index := .I]
pkgs[c(250, 500, (1:9)*1000)]
```

The JavaScript code chunk at the end is supposed to [simulate a click](https://github.com/timelyportfolio/sunburstR/issues/15) so that the legend box is checked and expanded automatically on launch, however it stopped working for me after a while (so you have to toggle it manually). Maybe a package update to `htmlwidgets` or `sunburstR` somehow broke it? Still, I left it in there in case you want to work it out yourself.

[^1]: Technically, Shiny apps are hosted at [Shinyapps.io](https://Shinyapps.io); however I will be distributing the links to the apps on this website.
[^2]: See [recommended workflow](https://bookdown.org/yihui/blogdown/workflow.html).